spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rentapp?createDatabaseIfNotExist=true 
    username: root
    password: 12345
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show_sql: true
    database: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    username: rentapp12345@gmail.com
    password: igrdoghsvbctrncc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    jpa:
      repositories:
        enabled: true
logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR
server:
  error:
    include-message: always
  port: 8085
application:
  jwt:
    secretKey: "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14